baseURL = "https://vasileios.github.io/ac-sc"
languageCode = "en-US"
defaultContentLanguage = "el"

title = "Algorithmic Composition"
theme = "hugo-theme-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true



#showVisitedLinks = false
  # Disable search function. It will hide search bar
#disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
#disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
#disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
#disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
#disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"
  
publishDir= "docs"

[params]
 themeVariant="black"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.el]
title = "Αλγοριθμική Σύνθεση"
weight = 1
languageName = "Ελληνικά"

[[Languages.el.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/Vasileios/ac-sc.git"
weight = 10

[[Languages.el.menu.shortcuts]]
name = "<i class='fa fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.el.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> creative-coding"
identifier = "CC"
url = "https://vasileios.github.io/creative-coding"
weight = 20

[[Languages.el.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.en]
title = "Documentation for Algorithmic Composition"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/Vasileios/ac-sc.git"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> creative-coding"
identifier = "CC"
url = "https://vasileios.github.io/creative-coding"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

